# # alpaca
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/alpaca_fmv2_final_0---projects-nlp-data-constanzam-stanford_alpaca-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name alpaca_aliases_0 --num_aliases 0
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/alpaca_fmv2_final_0---projects-nlp-data-constanzam-stanford_alpaca-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name alpaca_aliases_1 --num_aliases 1
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/alpaca_fmv2_final_0---projects-nlp-data-constanzam-stanford_alpaca-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name alpaca_aliases_2 --num_aliases 2
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/alpaca_fmv2_final_0---projects-nlp-data-constanzam-stanford_alpaca-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name alpaca_aliases_3 --num_aliases 3
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/alpaca_fmv2_final_0---projects-nlp-data-constanzam-stanford_alpaca-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name alpaca_aliases_4 --num_aliases 4
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/alpaca_fmv2_final_0---projects-nlp-data-constanzam-stanford_alpaca-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name alpaca_aliases_5 --num_aliases 5

# # lama
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama_fmv2_final_0---projects-nlp-data-constanzam-llama-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama_aliases_0 --num_aliases 0
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama_fmv2_final_0---projects-nlp-data-constanzam-llama-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama_aliases_1 --num_aliases 1
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama_fmv2_final_0---projects-nlp-data-constanzam-llama-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama_aliases_2 --num_aliases 2
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama_fmv2_final_0---projects-nlp-data-constanzam-llama-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama_aliases_3 --num_aliases 3
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama_fmv2_final_0---projects-nlp-data-constanzam-llama-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama_aliases_4 --num_aliases 4
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama_fmv2_final_0---projects-nlp-data-constanzam-llama-huggingface-ckpts-7B/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama_aliases_5 --num_aliases 5

# lama2
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama2_0--meta-llama-Llama-2-7b-hf/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama2_aliases_0 --num_aliases 0
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama2_0--meta-llama-Llama-2-7b-hf/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama2_aliases_1 --num_aliases 1
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama2_0--meta-llama-Llama-2-7b-hf/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama2_aliases_2 --num_aliases 2
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama2_0--meta-llama-Llama-2-7b-hf/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama2_aliases_3 --num_aliases 3
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama2_0--meta-llama-Llama-2-7b-hf/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama2_aliases_4 --num_aliases 4
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/llama2_0--meta-llama-Llama-2-7b-hf/predictions.json --aliases_path coastalcph/fm_aliases --exp_name llama2_aliases_5 --num_aliases 5

# flant5
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/flant5-xxl_0--google-flan-t5-xxl/predictions.json --aliases_path coastalcph/fm_aliases --exp_name flant5_aliases_0 --num_aliases 0
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/flant5-xxl_0--google-flan-t5-xxl/predictions.json --aliases_path coastalcph/fm_aliases --exp_name flant5_aliases_1 --num_aliases 1
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/flant5-xxl_0--google-flan-t5-xxl/predictions.json --aliases_path coastalcph/fm_aliases --exp_name flant5_aliases_2 --num_aliases 2
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/flant5-xxl_0--google-flan-t5-xxl/predictions.json --aliases_path coastalcph/fm_aliases --exp_name flant5_aliases_3 --num_aliases 3
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/flant5-xxl_0--google-flan-t5-xxl/predictions.json --aliases_path coastalcph/fm_aliases --exp_name flant5_aliases_4 --num_aliases 4
WANDB_MODE="offline" python -m evaluation --data_path coastalcph/fm_queries --predictions_path ../fm_predictions/fm_queries_v2/flant5-xxl_0--google-flan-t5-xxl/predictions.json --aliases_path coastalcph/fm_aliases --exp_name flant5_aliases_5 --num_aliases 5